"""Initial schema with all ORM models

Revision ID: 4c6b8ce0cf2c
Revises: 
Create Date: 2026-02-25 14:53:48.165693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6b8ce0cf2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('trade_date', sa.String(), nullable=False),
    sa.Column('final_decision', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('langfuse_trace_id', sa.String(), nullable=True),
    sa.Column('langfuse_trace_url', sa.String(), nullable=True),
    sa.Column('market_report', sa.Text(), nullable=True),
    sa.Column('sentiment_report', sa.Text(), nullable=True),
    sa.Column('news_report', sa.Text(), nullable=True),
    sa.Column('fundamentals_report', sa.Text(), nullable=True),
    sa.Column('valuation_result', sa.Text(), nullable=True),
    sa.Column('debate_history', sa.Text(), nullable=True),
    sa.Column('expert_opinions', sa.Text(), nullable=True),
    sa.Column('risk_assessment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_decisions_ticker_date', 'agent_decisions', ['ticker', 'trade_date'], unique=False)
    op.create_table('daily_nav',
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('positions_value', sa.Float(), nullable=False),
    sa.Column('daily_return', sa.Float(), nullable=False),
    sa.Column('cumulative_return', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('positions',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('raw_deep_research',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('report_markdown', sa.Text(), nullable=True),
    sa.Column('sources_json', sa.Text(), nullable=True),
    sa.Column('trigger_reason', sa.String(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_fundamentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('report_date', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_fundamentals_ticker'), 'raw_fundamentals', ['ticker'], unique=False)
    op.create_table('raw_macro_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('observation_date', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('trade_date', sa.String(), nullable=False),
    sa.Column('price_data_json', sa.Text(), nullable=True),
    sa.Column('indicators_json', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_market_ticker', 'raw_market_data', ['ticker', 'trade_date'], unique=False)
    op.create_table('raw_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('published_at', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_news_ticker'), 'raw_news', ['ticker'], unique=False)
    op.create_table('raw_social_sentiment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('raw_posts_json', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_data_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['agent_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_data_links_decision_id'), 'decision_data_links', ['decision_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['agent_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_decision_id'), 'trades', ['decision_id'], unique=False)
    op.create_index(op.f('ix_trades_ticker'), 'trades', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema from this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_ticker'), table_name='trades')
    op.drop_index(op.f('ix_trades_decision_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_decision_data_links_decision_id'), table_name='decision_data_links')
    op.drop_table('decision_data_links')
    op.drop_table('raw_social_sentiment')
    op.drop_index(op.f('ix_raw_news_ticker'), table_name='raw_news')
    op.drop_table('raw_news')
    op.drop_index('idx_raw_market_ticker', table_name='raw_market_data')
    op.drop_table('raw_market_data')
    op.drop_table('raw_macro_data')
    op.drop_index(op.f('ix_raw_fundamentals_ticker'), table_name='raw_fundamentals')
    op.drop_table('raw_fundamentals')
    op.drop_table('raw_deep_research')
    op.drop_table('positions')
    op.drop_table('daily_nav')
    op.drop_index('idx_decisions_ticker_date', table_name='agent_decisions')
    op.drop_table('agent_decisions')
    # ### end Alembic commands ###
